config/routes.rb
PicasaWebApp::Application.routes.draw do

  post "/comments", to: "comments#create"
  post "/sessions", to: "sessions#create"
  delete "/sessions", to: "sessions#destroy"

  get "albums", to: "albums#index", as: "albums"
  get "albums/show", to: "albums#show", as: "album"

  root to: "sessions#new"
  match "/auth/:provider/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"

end

app/models/album.rb
require 'open-uri'
require 'nokogiri'

class Album

  attr_accessor :url

  def self.fetch_albums user_id, key
    path = "/data/feed/api/user/#{user_id}"
    puts key
    puts get_request(path, key).body
    document = Nokogiri::HTML(get_request(path, key).body)
    document.css('feed entry').map do |node|
      {
        :title => node.css('title').first.text,
        :url => node.css('link').first[:href],
        :photo_url => node.css('content').first[:url],
        :published_at => node.css('published').first.text,
        :rights => node.css('rights').first.text
      }
    end
  end

  def self.fetch_pics path, key
    doc = Nokogiri::XML(get_request(path, key).body)
    doc.css('feed entry').map do |node|
      url = node.css('id').text
      id = url.split('/').last
      {
        :title => node.css('title').text,
        :url => node.css('media|content').first[:url],
        :published_at => node.css('published').text,
        :id => id,
        :pic_url => url
        #:comments => fetch_comments(id)
      }
    end
  end

private

  def fetch_comments(id)
    Comment.where("picture_id = '#{id}'").includes(:user).map do |comment|
      {
        :text => comment.text,
        :author => comment.user.username,
        :created_at => comment.created_at
      }
    end
  end

  def self.get_request path, headers
    https = Net::HTTP.new('picasaweb.google.com', 443)
    https.use_ssl = true
    headers = {
      'Authorization' => "GoogleLogin auth=#{headers}"
    }
    res = https.get(path, headers)
  end
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :name, :provider, :uid

  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    if !logged_in?
      redirect_to root_url and return
    end   
    @albums = Album.fetch_albums( session[:user_id], session[:key])
  end

  def show
    if !logged_in?
      redirect_to root_url and return
    end   
    @album_pics = Album.fetch_pics( params[:album_url], session[:key])[0..2]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def logged_in?
    if session[:user_id] && session[:key]
      return true
    else
      return false 
    end
  end
  helper_method :logged_in?

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  require 'uri'
  require 'net/http'
  require 'net/https'

  def create

    @desc = params[:desc]
    @pic_id = params[:pic_url].split("/")[-1]
    path = params[:pic_url].split("/")[-5..-1].join("/")

    https = Net::HTTP.new('picasaweb.google.com', 443)
    https.use_ssl = true
    path = '/data/feed/api/user/'+ path #deepakvig/albumid/5821407449002245793/photoid/5837016705233353714'
    headers = {
      "Content-Type" => "application/atom+xml",
      'Authorization' => "GoogleLogin auth=#{session[:key]}"
    }
    resp = https.post(path, build_request_body(@desc), headers)
  end

  private

  def build_request_body(comment)
    return "<entry xmlns='http://www.w3.org/2005/Atom'><content>#{comment}</content><category scheme=\"http://schemas.google.com/g/2005#kind\" term=\"http://schemas.google.com/photos/2007#comment\"/></entry>"
  end
end

app/controllers/sessions_controller.rb
require 'cgi'

class SessionsController < ApplicationController
  def new
    if logged_in?
      redirect_to albums_url and return
    end
  end

  def create
    key = authenticate
    if key.blank?
      redirect_to root_url, notice: "Not able to Login"
    else
      session[:key] = key
      session[:user_id] = params[:user_id]
      redirect_to albums_url
    end
  end

  def destroy
    session[:user_id] = nil
    session[:key] = nil
    redirect_to root_url, notice: "Signed out!" and return
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end

  private

  def authenticate
    https = Net::HTTP.new('google.com', 443)
    https.use_ssl = true
    path = '/accounts/ClientLogin'
    headers = {
      "Content-Type" => "application/x-www-form-urlencoded"
    }
    body = inline_query ({
          "accountType" => "HOSTED_OR_GOOGLE",
          "Email"       => 'deepakvig',
          "Passwd"      => 'dee180pak$',
          "service"     => "lh2",
          "source"      => "ruby-picasa"
        })
    
    resp = https.post(path, body, headers)
    response = resp.body.split("\n").map { |v| v.split("=") }
    params = Hash[response]
    params["Auth"]
  end 

  def inline_query(query)
    query.map do |key, value|
      dasherized = key.to_s.gsub("_", "-")
      "#{CGI.escape(dasherized)}=#{CGI.escape(value.to_s)}"
    end.join("&")
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def convert_date date
    date.to_date.strftime('%b %d, %Y')
  end

  def user_signed_in?
    false
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/albums/index.html.slim
h2 Albums:
br
- if @albums.present?
  .row-fluid
    - @albums.each_slice(4).each do |albums|
      ul
        - albums.each do |album|
          li.span3
            .caption
              = link_to image_tag("#{album[:photo_url]}", class: "img-album"), album_path(:album_url => album[:url], :rights => album[:rights])
              h3
                = link_to album[:title], album_path(:album_url => album[:url])
              p.created_at
                = convert_date album[:published_at]
- else
  p No albums were found.

app/views/albums/show.html.slim
h2 Album Pictures:
br
- @album_pics.each_slice(4) do |pictures|
  p
    b Showing upto 3 pics for this album.
  .row-fluid
    ul
      - pictures.first(3).each do |picture|
        li.span4
          .caption
            h3= picture[:title]
          img[src="#{picture[:url]}" class="img-pic"]
          .caption
            p.created_at
              = convert_date picture[:published_at]
          div[class="#{picture[:id]}"]
          = render 'comments/form', :url => picture[:pic_url] 

app/views/comments/_form.html.slim
= form_tag '/comments', :remote => true do
  = text_field_tag 'desc' 
  = hidden_field_tag 'pic_url', url
  br
  = submit_tag 'Add Comment' 

app/views/comments/create.js.slim
'$('.#{@pic_id}').append('<div><p>#{@desc}</p></div><hr/>');

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Picasa
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          a.brand href="#{root_url}" Picasa
          .nav-collapse.collapse.navbar-responsive-collapse
            ul.nav
              li.active
                a Home
              li
                a href="#" About Me
            - if session[:user_id]
              ul.nav.pull-right
                li
                  a href="#"
                    = session[:user_id]
                li.divider-vertical
                li= link_to "Sign out", '/sessions', :method => :delete

    .container
      = yield